#!/bin/bash

for DIST in intrepid jaunty karmic lucid
do HEADER=`cat debian/changelog-base | head -1 | sed -e 's/karmic/intrepid/g' -e 's/)/intrepid)/g'` 
echo $HEADER > debian/changelog
echo "  * Rebuild for intrepid " >> debian/changelog
echo "" >> debian/changelog
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog-cvs >> debian/changelog
debuild -S -sa -kB734D1F5
done

cd ..
dput ppa:chris-debenham/lyricue precue*_source.changes

