#!/bin/bash

for DIST in precise quantal raring saucy trusty utopic vivid
do echo Building for $DIST
HEADER=`cat debian/changelog-base | head -1`
echo $HEADER | sed -e "s/utopic/$DIST/g" -e "s/)/${DIST})/g"  > debian/changelog
echo "" >> debian/changelog
echo "  * Rebuild for ${DIST}" >> debian/changelog
echo "" >> debian/changelog
echo " -- Chris Debenham <chris@adebenham.com> " `date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog-base >> debian/changelog
debuild -S -sa -kB734D1F5
done

cd ..
dput ppa:chris-debenham/lyricue precue*_source.changes
