<?PHP
function about() {
    ?>
<B>Lyricue:</B><BR>
is a GTK Perl program that interacts with MySQL databases to provide a fast and powerful lyrics display system. lyricue responds quickly and, best of all, is free. lyricue is licensed under the GNU GPL and, as a result, undergoes considerable change from week to week and month to month so check the website for the newest version.<BR><BR>

Lyricue was written for Erina Community Church by Chris Debenham.<BR>
Email: <A HREF=mailto:chris@adebenham.com>chris@adebenham.com</A>. 
WWW: <A HREF=http://www.lyricue.org/>Lyricue website</A>

<BR><BR>
<B>Precue:</B><BR>
Lyricue enables remote access to the lyrics and bible databases which Lyricue uses. It facilitates the modification of any Lyricue playlist, the viewing of available songs and the generation of song usage profiles. For security reasons, no provision for deleting songs is made in this version. Precue is implemented in as a group of PHP4 webpages suitable for use with any PHP enabled server.</B><BR><BR>

Lyricue was written for Erina Community Baptist Church by Clint Turner.<BR>
Email: <A HREF=mailto:ldsf@clintturner.com>ldsf@clintturner.com</A>. 

<?PHP
}
?>

