<?PHP

//for convenience we import our
//session variables. This is still
//much safer than using register_globals
//because we know the source.
$fver = $_SESSION['fver'];
$lyricuever = $_SESSION['lyricuever'];
$bible = $_SESSION['bible'];
$biblename = $_SESSION['biblename'];
$db_user = $_SESSION['db_user'];
$db_host = $_SESSION['db_host'];
$db_pwd = $_SESSION['db_pwd'];

$media = $_SESSION['media'];
$media_path = $_SESSION['media_path'];


